=== maudmld/XML_portofolio/Exo_final.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT lettres (lettre+) >
<!ELEMENT lettre (en-tête, corps, pied)>
<!ELEMENT en-tête (émetteur?, date, destinataire)>
<!ELEMENT émetteur (#PCDATA) >
<!ELEMENT date (#PCDATA)>
<!ATTLIST date calendar (julian | gregorian | chinese | other) #REQUIRED>
<!ATTLIST date when CDATA #REQUIRED>
<!ELEMENT destinataire (nom, prénom, adresse?)>
<!ELEMENT nom (#PCDATA) >
<!ELEMENT prénom (#PCDATA)>
<!ELEMENT adresse (#PCDATA)>
<!ELEMENT corps (paragraphe+)>
<!ELEMENT paragraphe (personne?, lieu?, évènement?)>
<!ELEMENT personne (#PCDATA) >
<!ELEMENT lieu (#PCDATA) >
<!ELEMENT évènement (#PCDATA) >
<!ELEMENT pied (formule_fin, auteur?, signature, post-scriptum?)>
<!ELEMENT formule_fin (#PCDATA) >
<!ELEMENT auteur (nom, prénom, adresse?) >
<!ELEMENT signature (#PCDATA) >
<!ELEMENT post-scriptum (#PCDATA) >

=== maudmld/XML_portofolio/Exo_final.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE lettres SYSTEM 'Exo_final.dtd'>
<lettres>
    <lettre>
        <en-tête>
            <date when="" calendar="gregorian"></date>
            <destinataire>
                <nom></nom>
                <prénom></prénom>
            </destinataire>
        </en-tête>
        <corps>
            <paragraphe></paragraphe>
        </corps>
        <pied>
            <formule_fin></formule_fin>
            <auteur>
                <nom></nom>
                <prénom></prénom>
                <adresse></adresse>
            </auteur>
            <signature></signature>
            <post-scriptum></post-scriptum>
        </pied>
    </lettre>
    <lettre>
        <en-tête>
            <date when='2025' calendar="gregorian"></date>
            <destinataire>
                <nom></nom>
                <prénom></prénom>
            </destinataire>
        </en-tête>
        <corps>
            <paragraphe></paragraphe>
        </corps>
        <pied>
            <formule_fin></formule_fin>
            <auteur>
                <nom></nom>
                <prénom></prénom>
                <adresse></adresse>
            </auteur>
            <signature></signature>
            <post-scriptum></post-scriptum>
        </pied>
    </lettre>
    <lettre>
        <en-tête>
        <date when="" calendar="gregorian"></date>
        <destinataire>
            <nom></nom>
            <prénom></prénom>
        </destinataire>
    </en-tête>
    <corps>
        <paragraphe></paragraphe>
    </corps>
    <pied>
        <formule_fin></formule_fin>
        <auteur>
            <nom></nom>
            <prénom></prénom>
            <adresse></adresse>
        </auteur>
        <signature></signature>
        <post-scriptum></post-scriptum>
    </pied>
    </lettre>
</lettres>
